-- CreateEnum
CREATE TYPE "Status" AS ENUM ('CREATED', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELED');

-- CreateTable
CREATE TABLE "USERS" (
    "ID" UUID NOT NULL,
    "USERNAME" VARCHAR(128) NOT NULL,
    "CPF" VARCHAR(11) NOT NULL,
    "PASSWORD" VARCHAR(60) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "USERS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ORDERS" (
    "ID" UUID NOT NULL,
    "NUMBER" INTEGER NOT NULL,
    "DELIVERY_DATE" TIMESTAMPTZ NOT NULL,
    "DELIVERY_STREET" VARCHAR(128) NOT NULL,
    "DELIVERY_NUMBER" SMALLINT NOT NULL,
    "DELIVERY_NEIGHBORHOOD" VARCHAR(128) NOT NULL,
    "DELIVERY_CITY" VARCHAR(64) NOT NULL,
    "DELIVERY_STATE" VARCHAR(64) NOT NULL,
    "DELIVERY_ZIP_CODE" VARCHAR(8) NOT NULL,
    "DELIVERY_COMPLEMENT" VARCHAR(128) NOT NULL,
    "STATUS" "Status" NOT NULL,
    "CUSTOMER_ID" UUID NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "ORDERS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "ORDER_ITEMS" (
    "ID" UUID NOT NULL,
    "ORDER_ID" UUID NOT NULL,
    "PRODUCT_ID" UUID NOT NULL,
    "QUANTITY" INTEGER NOT NULL,
    "UNIT_PRICE_AT_PURCHASE" DECIMAL(10,2) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "ORDER_ITEMS_pkey" PRIMARY KEY ("ID")
);

-- CreateTable
CREATE TABLE "PRODUCTS" (
    "ID" UUID NOT NULL,
    "DESCRIPTION" VARCHAR(128) NOT NULL,
    "PRICE" DECIMAL(10,2) NOT NULL,
    "CREATED_AT" TIMESTAMPTZ NOT NULL,

    CONSTRAINT "PRODUCTS_pkey" PRIMARY KEY ("ID")
);

-- CreateIndex
CREATE UNIQUE INDEX "USERS_CPF_key" ON "USERS"("CPF");

-- CreateIndex
CREATE UNIQUE INDEX "ORDERS_NUMBER_key" ON "ORDERS"("NUMBER");

-- CreateIndex
CREATE INDEX "ORDERS_NUMBER_idx" ON "ORDERS"("NUMBER");

-- CreateIndex
CREATE INDEX "ORDERS_STATUS_idx" ON "ORDERS"("STATUS");

-- AddForeignKey
ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_CUSTOMER_ID_fkey" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "USERS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_ORDER_ID_fkey" FOREIGN KEY ("ORDER_ID") REFERENCES "ORDERS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ORDER_ITEMS" ADD CONSTRAINT "ORDER_ITEMS_PRODUCT_ID_fkey" FOREIGN KEY ("PRODUCT_ID") REFERENCES "PRODUCTS"("ID") ON DELETE RESTRICT ON UPDATE CASCADE;
